---
title: shop
---
erDiagram
    PRODUCT {
        int id PK
        int price
        string name
    }
    CUSTOMER {
        string email
        int id PK
        string name
    }
    ORDER {
        int quantity
        string date
        int id PK
        int customer FK
        int product FK
    }

    ORDER }o--|| PRODUCT : "references"
    ORDER }o--|| CUSTOMER : "references"